# Generated by Django 5.2.6 on 2025-09-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_userprofile_is_verified_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
